### PR TITLE
Rib 186 add ability to click on users profile in place reviews add text review

### PR DESCRIPTION
**Pull request by marthubner**
### RIB-186 Add ability to click on users profile in place reviews

- making a fragment from users review card, using it on user/interest page
- fixing some minor css glitches
- fixing screen height for mobile browser - (using dvh instead of vh unit)
**BEFORE**
users-reviews-before
place-reviews-before
dropdown-before
register-before
place-before

**AFTER**
users-reviews-after
place-reviews-after
dropdown-after
register-after
place-after

### CODE REVIEW

**Review by vdrfg — APPROVED** [review]
I would slightly decrease the arrow size to match the font size, otherwise good. 👍

image

**Review by MatejFrnka — APPROVED** [review]

**Comment by marthubner** [comment]
> I would slightly decrease the arrow size to match the font size, otherwise good. 👍
> 
> image

Good point.
image

**Comment by dondowoldo** [comment]
Very nice 🙂 Personally I am not the biggest fan of displaying seconds in the timestamp as well, but I can live with it 😅

**Review by dondowoldo — APPROVED** [review]

**Comment by vdrfg** [comment]
> Very nice 🙂 Personally I am not the biggest fan of displaying seconds in the timestamp as well, but I can live with it 😅

It can save lives!

**Pull request merged**
